Repository hassio-addons/addon-zerotier, pull requests merged in 2022-03, with the labels that each got.

#139 :lock: Sign add-on with Codenotary Community Attestation Service (CAS)
  .github/workflows/deploy.yaml
  zerotier/build.yaml
  zerotier/config.yaml
Labels: enhancement

#140 :books: Add My buttons to documentation
  zerotier/DOCS.md
Labels: documentation

#141 ⬆️ Upgrades ZeroTier One to 1.8.5
  zerotier/Dockerfile
Labels: dependencies

#142 ⬆️ Upgrades ZeroTier One to 1.8.6
  zerotier/Dockerfile
Labels: dependencies

#143 Fix authtoken.secret file path
  zerotier/rootfs/etc/cont-init.d/zerotier.sh
Labels: bugfix

#144 :books: Fix documentation link
  zerotier/DOCS.md
Labels: documentation
