Repository hassio-addons/addon-zerotier, pull requests merged in 2023-03, with the labels that each got.

#165 :fireworks: Updates maintenance/license year to 2023
  LICENSE.md
  README.md
  zerotier/.README.j2
  zerotier/DOCS.md
Labels: dependencies

#166 ⬆️ Upgrades add-on base image to 13.1.3
  zerotier/Dockerfile
  zerotier/build.yaml
Labels: dependencies

#167 ⬆️ Upgrades ZeroTier One to 1.10.4
  zerotier/Dockerfile
Labels: dependencies

#170 Add Renovate for dependency management
  .github/dependabot.yaml
  .github/renovate.json
  zerotier/Dockerfile
Labels: maintenance

#175 Fix broken URL
  zerotier/DOCS.md
Labels: documentation
